version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8081:80"
        links:
            - app
        hostname: lvsproject
        domainname: lvsproject.local

    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
            - cache

    database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
            - "MYSQL_USER=${DB_USERNAME}"
            - "MYSQL_PASSWORD=${DB_PASSWORD}"
            - "MYSQL_DATABASE=${DB_DATABASE}"
        ports:
            - "${DB_OUTER_PORT}:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        env_file:
            - .env
    cache:
        image: redis:3.0
        ports:
            - "63791:6379"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - "8082:80"
        links:
          - database
        environment:
          - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
          - "PMA_PORT=3306"
          - "PMA_HOST=database"
          - "PMA_USER=${DB_USERNAME}"
          - "PMA_PASSWORD=${DB_PASSWORD}"
        env_file:
          - .env