version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8081:80"
        links:
            - app
        hostname: vmmsmp3
        domainname: vmmsmp3.local
    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
            - cache
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=localhost"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
            - "APP_ENV=develop"
            - "APP_DEBUG=true"
    database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=test"
        ports:
            - "33061:3306"
        volumes:
            - ./mysql:/var/lib/mysql
    cache:
        image: redis:3.0
        ports:
            - "63791:6379"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - "8082:80"
        links:
          - database
        environment:
          - "MYSQL_ROOT_PASSWORD=secret"
          - "PMA_PORT=3306"
          - "PMA_HOST=database"
          - "PMA_USER=root"
          - "PMA_PASSWORD=secret"